//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.17 at 05:41:36 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.Soap.api.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.api.Soap.inte;
